"""Golden Scenarios — 10 predefined scenarios covering all domains."""
from __future__ import annotations

from typing import Any

# 10 Golden Scenarios
GOLDEN_SCENARIOS: dict[str, dict[str, Any]] = {
    "GS-01": {
        "id": "GS-01",
        "name": "Energy Management",
        "description": "Monitor energy intensity, optimize consumption, reduce carbon footprint",
        "tags": ["energy", "kpi", "dashboard"],
        "assets": {"GA-05": "primary", "GA-06": "secondary", "GA-03": "contributor"},
        "kpis": ["energy_intensity", "carbon_footprint", "cost_per_sqm"],
        "dashboards": [{"type": "energy", "widgets": ["chart", "gauge", "kpi_card", "trend"]}],
        "alarms": [{"severity": "P2", "condition": "energy_intensity > 1.5", "workflow": "sop-energy-alarm"}],
        "scenes": [{"type": "energy", "bindings": ["bim", "gis"]}],
    },
    "GS-02": {
        "id": "GS-02",
        "name": "HVAC Optimization",
        "description": "Auto-adjust temperature based on occupancy and outdoor conditions",
        "tags": ["hvac", "optimization", "comfort"],
        "assets": {"GA-03": "primary", "GA-04": "primary", "GA-12": "contributor"},
        "kpis": ["hvac_efficiency", "occupant_comfort"],
        "dashboards": [{"type": "hvac", "widgets": ["chart", "gauge", "3d"]}],
        "alarms": [{"severity": "P3", "condition": "supply_air_temp > 25", "workflow": "sop-hvac-alarm"}],
        "scenes": [{"type": "hvac", "bindings": ["bim"]}],
    },
    "GS-03": {
        "id": "GS-03",
        "name": "Water Management",
        "description": "Leak detection, usage monitoring, flow optimization",
        "tags": ["water", "leak_detection", "monitoring"],
        "assets": {"GA-07": "primary", "GA-12": "contributor"},
        "kpis": ["water_usage_rate"],
        "dashboards": [{"type": "water", "widgets": ["chart", "gauge", "map"]}],
        "alarms": [{"severity": "P2", "condition": "flow_rate < threshold", "workflow": "sop-water-leak"}],
        "scenes": [{"type": "water", "bindings": ["bim"]}],
    },
    "GS-04": {
        "id": "GS-04",
        "name": "Security & Access",
        "description": "Incident response workflow, access control monitoring",
        "tags": ["security", "access", "incident"],
        "assets": {"GA-08": "primary", "GA-09": "primary", "GA-17": "contributor"},
        "kpis": ["security_incident_rate", "access_control_pass_rate"],
        "dashboards": [{"type": "security", "widgets": ["alarm_list", "map", "table"]}],
        "alarms": [{"severity": "P1", "condition": "motion_detected == true", "workflow": "sop-security-incident"}],
        "scenes": [{"type": "security", "bindings": ["3d"]}],
    },
    "GS-05": {
        "id": "GS-05",
        "name": "Transport & Parking",
        "description": "Elevator availability monitoring, parking occupancy optimization",
        "tags": ["transport", "parking", "elevator"],
        "assets": {"GA-10": "primary", "GA-11": "primary", "GA-16": "contributor", "GA-18": "contributor"},
        "kpis": ["elevator_availability", "parking_occupancy"],
        "dashboards": [{"type": "transport", "widgets": ["kpi_card", "chart", "list"]}],
        "alarms": [{"severity": "P3", "condition": "elevator_availability < 90%", "workflow": "sop-elevator-maintenance"}],
        "scenes": [{"type": "transport", "bindings": ["bim"]}],
    },
    "GS-06": {
        "id": "GS-06",
        "name": "Environment Monitoring",
        "description": "Air quality tracking, thermal comfort optimization",
        "tags": ["environment", "air_quality", "comfort"],
        "assets": {"GA-12": "primary", "GA-03": "contributor"},
        "kpis": ["occupant_comfort", "carbon_footprint"],
        "dashboards": [{"type": "environment", "widgets": ["gauge", "chart", "heatmap"]}],
        "alarms": [{"severity": "P2", "condition": "pm25 > 35", "workflow": "sop-environment-alarm"}],
        "scenes": [{"type": "environment", "bindings": ["gis"]}],
    },
    "GS-07": {
        "id": "GS-07",
        "name": "Production Monitoring",
        "description": "OEE tracking, alarm-to-workorder closure loop",
        "tags": ["production", "oee", "alarm"],
        "assets": {"GA-13": "primary", "GA-14": "primary"},
        "kpis": ["equipment_availability", "oee_total"],
        "dashboards": [{"type": "production", "widgets": ["kpi_card", "chart", "alarm_list"]}],
        "alarms": [{"severity": "P1", "condition": "spindle_speed == 0 AND status != idle", "workflow": "sop-production-alarm"}],
        "scenes": [{"type": "production", "bindings": ["bim"]}],
    },
    "GS-08": {
        "id": "GS-08",
        "name": "Fire Safety",
        "description": "Fire alarm escalation, evacuation workflow, response time tracking",
        "tags": ["fire", "safety", "emergency"],
        "assets": {"GA-15": "primary", "GA-08": "contributor"},
        "kpis": ["fire_alarm_response_time", "emergency_evacuation_time"],
        "dashboards": [{"type": "fire", "widgets": ["alarm_list", "map", "kpi_card"]}],
        "alarms": [{"severity": "P1", "condition": "alarm_status == fire", "workflow": "sop-fire-emergency"}],
        "scenes": [{"type": "fire", "bindings": ["bim", "3d"]}],
    },
    "GS-09": {
        "id": "GS-09",
        "name": "Integrated Operations",
        "description": "Dashboard + LargeScreen + KPI + Alarm + Workflow integrated scenario",
        "tags": ["integrated", "operations", "dashboard", "largescreen"],
        "assets": {"GA-01": "primary", "GA-05": "contributor", "GA-03": "contributor", "GA-15": "contributor"},
        "kpis": ["energy_intensity", "equipment_availability", "occupant_comfort"],
        "dashboards": [{"type": "overview", "widgets": ["chart", "gauge", "kpi_card", "alarm_list", "3d"]}],
        "largescreens": [{"type": "lobby", "layouts": 3, "rotate_interval": 30}],
        "alarms": [{"severity": "P2", "condition": "multiple", "workflow": "sop-integrated"}],
        "scenes": [{"type": "overview", "bindings": ["bim", "gis", "3d"]}],
    },
    "GS-010": {
        "id": "GS-010",
        "name": "Zero-Code Assembly",
        "description": "Full zero-code assembly pipeline: New Project → Import BIM → Connect → Discover → Classify → Instantiate → Bind → Generate Apps → Publish",
        "tags": ["zero-code", "assembly", "e2e"],
        "assets": {f"GA-{i:02d}": "primary" for i in range(1, 21)},
        "kpis": ["energy_intensity", "equipment_availability", "occupant_comfort"],
        "dashboards": [{"type": "overview", "widgets": ["chart", "gauge", "kpi_card"]}],
        "largescreens": [{"type": "kiosk", "layouts": 2, "rotate_interval": 30}],
        "alarms": [{"severity": "P2", "condition": "any", "workflow": "sop-general"}],
        "scenes": [{"type": "overview", "bindings": ["bim", "gis", "3d"]}],
    },
}
