"""Golden Assets — 20 predefined assets covering all 14 categories with cross-layer validation."""
from __future__ import annotations

import logging
from dataclasses import dataclass, field
from typing import Any

logger = logging.getLogger(__name__)

# 20 Golden Assets with full classification coverage
GOLDEN_ASSETS: dict[str, dict[str, Any]] = {
    "GA-01": {
        "id": "GA-01",
        "code": "asset.park.spatial.building_main",
        "name": "Main Building",
        "category": "building",
        "domain": "spatial",
        "description": "Primary building structure",
        "points": [
            {"id": "point-01-01", "code": "point.park.spatial.building_main.structural_health", "semantic_type": "health_index", "unit": "%"},
        ],
        "capabilities": ["capability.spatial.inspect"],
        "template_ref": "template.building",
        "bindings": [{"source": "bim", "source_id": "ifc-guid-building-001", "lod": 300}],
        "relationships": [],
    },
    "GA-02": {
        "id": "GA-02",
        "code": "asset.park.spatial.building_secondary",
        "name": "Secondary Building",
        "category": "building",
        "domain": "spatial",
        "points": [],
        "capabilities": [],
        "template_ref": "template.building",
        "bindings": [],
        "relationships": [{"type": "contains", "target": "GA-01", "direction": "bidirectional"}],
    },
    "GA-03": {
        "id": "GA-03",
        "code": "asset.park.hvac.ahu_01",
        "name": "AHU-01 Main Air Handler",
        "category": "hvac",
        "domain": "hvac",
        "points": [
            {"id": "point-03-01", "code": "point.park.hvac.ahu_01.supply_air_temp", "semantic_type": "temperature", "unit": "degC"},
            {"id": "point-03-02", "code": "point.park.hvac.ahu_01.return_air_temp", "semantic_type": "temperature", "unit": "degC"},
            {"id": "point-03-03", "code": "point.park.hvac.ahu_01.fan_speed", "semantic_type": "rotational_speed", "unit": "Hz"},
        ],
        "capabilities": ["capability.hvac.set_temperature", "capability.hvac.set_fan_speed"],
        "template_ref": "template.hvac.ahu",
        "bindings": [{"source": "bim", "source_id": "ifc-hvac-ahu-001", "lod": 300}],
        "relationships": [{"type": "feeds", "target": "GA-01", "direction": "directed"}],
    },
    "GA-04": {
        "id": "GA-04",
        "code": "asset.park.hvac.chiller_01",
        "name": "Chiller-01",
        "category": "hvac",
        "domain": "hvac",
        "points": [
            {"id": "point-04-01", "code": "point.park.hvac.chiller_01.cooling_output", "semantic_type": "power", "unit": "kW"},
            {"id": "point-04-02", "code": "point.park.hvac.chiller_01.electrical_input", "semantic_type": "power", "unit": "kW"},
        ],
        "capabilities": ["capability.hvac.set_cooling_setpoint"],
        "template_ref": "template.hvac.chiller",
        "bindings": [{"source": "bim", "source_id": "ifc-hvac-chiller-001", "lod": 300}],
        "relationships": [{"type": "feeds", "target": "GA-03", "direction": "directed"}],
    },
    "GA-05": {
        "id": "GA-05",
        "code": "asset.park.energy.substation_01",
        "name": "Main Substation",
        "category": "energy",
        "domain": "energy",
        "points": [
            {"id": "point-05-01", "code": "point.park.energy.substation_01.total_kw", "semantic_type": "power", "unit": "kW"},
            {"id": "point-05-02", "code": "point.park.energy.substation_01.total_kwh", "semantic_type": "energy", "unit": "kWh"},
        ],
        "capabilities": ["capability.energy.read_meter"],
        "template_ref": "template.energy.substation",
        "bindings": [{"source": "3d", "source_id": "glTF-energy-substation-001", "lod": 200}],
        "relationships": [{"type": "supplies", "target": "GA-01", "direction": "directed"}],
    },
    "GA-06": {
        "id": "GA-06",
        "code": "asset.park.energy.pv_array_01",
        "name": "PV Array-01",
        "category": "energy",
        "domain": "energy",
        "points": [
            {"id": "point-06-01", "code": "point.park.energy.pv_01.output_kw", "semantic_type": "power", "unit": "kW"},
            {"id": "point-06-02", "code": "point.park.energy.pv_01.irradiance", "semantic_type": "illuminance", "unit": "W/m2"},
        ],
        "capabilities": ["capability.energy.read_pv"],
        "template_ref": "template.energy.pv",
        "bindings": [{"source": "gis", "source_id": "geojson-pv-array-001", "lod": 100}],
        "relationships": [{"type": "feeds", "target": "GA-05", "direction": "directed"}],
    },
    "GA-07": {
        "id": "GA-07",
        "code": "asset.park.water.pump_station_01",
        "name": "Water Pump Station",
        "category": "water",
        "domain": "water",
        "points": [
            {"id": "point-07-01", "code": "point.park.water.pump_01.flow_rate", "semantic_type": "volumetric_flow_rate", "unit": "m3/h"},
            {"id": "point-07-02", "code": "point.park.water.pump_01.pressure", "semantic_type": "pressure", "unit": "Pa"},
        ],
        "capabilities": ["capability.water.control_pump"],
        "template_ref": "template.water.pump",
        "bindings": [{"source": "bim", "source_id": "ifc-water-pump-001", "lod": 200}],
        "relationships": [],
    },
    "GA-08": {
        "id": "GA-08",
        "code": "asset.park.security.cctv_01",
        "name": "CCTV Camera-01",
        "category": "security",
        "domain": "security",
        "points": [
            {"id": "point-08-01", "code": "point.park.security.cctv_01.motion_detected", "semantic_type": "boolean", "unit": ""},
        ],
        "capabilities": ["capability.security.view_feed"],
        "template_ref": "template.security.camera",
        "bindings": [{"source": "3d", "source_id": "glTF-camera-001", "lod": 100}],
        "relationships": [{"type": "monitors", "target": "GA-01", "direction": "directed"}],
    },
    "GA-09": {
        "id": "GA-09",
        "code": "asset.park.security.access_control_01",
        "name": "Access Control-01",
        "category": "security",
        "domain": "security",
        "points": [
            {"id": "point-09-01", "code": "point.park.security.access_01.door_status", "semantic_type": "status", "unit": ""},
        ],
        "capabilities": ["capability.security.unlock_door"],
        "template_ref": "template.security.access",
        "bindings": [],
        "relationships": [{"type": "controls", "target": "GA-01", "direction": "directed"}],
    },
    "GA-10": {
        "id": "GA-10",
        "code": "asset.park.transport.elevator_01",
        "name": "Elevator-01",
        "category": "transport",
        "domain": "transport",
        "points": [
            {"id": "point-10-01", "code": "point.park.transport.elevator_01.current_floor", "semantic_type": "integer", "unit": ""},
            {"id": "point-10-02", "code": "point.park.transport.elevator_01.status", "semantic_type": "status", "unit": ""},
        ],
        "capabilities": ["capability.transport.call_elevator"],
        "template_ref": "template.transport.elevator",
        "bindings": [{"source": "bim", "source_id": "ifc-elevator-001", "lod": 200}],
        "relationships": [{"type": "depends_on", "target": "GA-01", "direction": "directed"}],
    },
    "GA-11": {
        "id": "GA-11",
        "code": "asset.park.transport.parking_gate_01",
        "name": "Parking Gate-01",
        "category": "transport",
        "domain": "transport",
        "points": [
            {"id": "point-11-01", "code": "point.park.transport.parking_01.occupied_spaces", "semantic_type": "count", "unit": ""},
        ],
        "capabilities": ["capability.transport.open_gate"],
        "template_ref": "template.transport.parking",
        "bindings": [],
        "relationships": [],
    },
    "GA-12": {
        "id": "GA-12",
        "code": "asset.park.environment.air_quality_01",
        "name": "Air Quality Sensor-01",
        "category": "environment",
        "domain": "environment",
        "points": [
            {"id": "point-12-01", "code": "point.park.environment.aq_01.pm25", "semantic_type": "concentration", "unit": "ug/m3"},
            {"id": "point-12-02", "code": "point.park.environment.aq_01.co2", "semantic_type": "concentration", "unit": "ppm"},
        ],
        "capabilities": ["capability.environment.read_sensor"],
        "template_ref": "template.environment.sensor",
        "bindings": [{"source": "gis", "source_id": "geojson-aq-sensor-001", "lod": 100}],
        "relationships": [{"type": "monitors", "target": "GA-01", "direction": "directed"}],
    },
    "GA-13": {
        "id": "GA-13",
        "code": "asset.factory.production.cnc_01",
        "name": "CNC Machine-01",
        "category": "production",
        "domain": "production",
        "points": [
            {"id": "point-13-01", "code": "point.factory.production.cnc_01.spindle_speed", "semantic_type": "rotational_speed", "unit": "Hz"},
            {"id": "point-13-02", "code": "point.factory.production.cnc_01.part_count", "semantic_type": "count", "unit": ""},
        ],
        "capabilities": ["capability.production.start_cnc", "capability.production.stop_cnc"],
        "template_ref": "template.production.cnc",
        "bindings": [{"source": "bim", "source_id": "ifc-production-cnc-001", "lod": 300}],
        "relationships": [{"type": "depends_on", "target": "GA-05", "direction": "directed"}],
    },
    "GA-14": {
        "id": "GA-14",
        "code": "asset.factory.production.conveyor_01",
        "name": "Conveyor-01",
        "category": "production",
        "domain": "production",
        "points": [
            {"id": "point-14-01", "code": "point.factory.production.conveyor_01.speed", "semantic_type": "velocity", "unit": "m/s"},
        ],
        "capabilities": ["capability.production.start_conveyor"],
        "template_ref": "template.production.conveyor",
        "bindings": [],
        "relationships": [{"type": "feeds", "target": "GA-13", "direction": "directed"}],
    },
    "GA-15": {
        "id": "GA-15",
        "code": "asset.park.fire.panel_01",
        "name": "Fire Alarm Panel-01",
        "category": "fire",
        "domain": "fire",
        "points": [
            {"id": "point-15-01", "code": "point.park.fire.panel_01.alarm_status", "semantic_type": "status", "unit": ""},
        ],
        "capabilities": ["capability.fire.trigger_alarm"],
        "template_ref": "template.fire.panel",
        "bindings": [{"source": "bim", "source_id": "ifc-fire-panel-001", "lod": 200}],
        "relationships": [{"type": "monitors", "target": "GA-01", "direction": "directed"}],
    },
    "GA-16": {
        "id": "GA-16",
        "code": "asset.park.elevator.group_a_01",
        "name": "Elevator Group A",
        "category": "elevator",
        "domain": "elevator",
        "points": [
            {"id": "point-16-01", "code": "point.park.elevator.group_a_01.availability", "semantic_type": "percentage", "unit": "%"},
        ],
        "capabilities": ["capability.elevator.group_control"],
        "template_ref": "template.elevator.group",
        "bindings": [],
        "relationships": [{"type": "contains", "target": "GA-10", "direction": "directed"}],
    },
    "GA-17": {
        "id": "GA-17",
        "code": "asset.park.access.main_gate_01",
        "name": "Main Gate Access",
        "category": "access",
        "domain": "access",
        "points": [
            {"id": "point-17-01", "code": "point.park.access.main_gate_01.pass_count", "semantic_type": "count", "unit": ""},
        ],
        "capabilities": ["capability.access.open_gate"],
        "template_ref": "template.access.gate",
        "bindings": [],
        "relationships": [{"type": "controls", "target": "GA-01", "direction": "directed"}],
    },
    "GA-18": {
        "id": "GA-18",
        "code": "asset.park.parking.zone_a_01",
        "name": "Parking Zone A",
        "category": "parking",
        "domain": "parking",
        "points": [
            {"id": "point-18-01", "code": "point.park.parking.zone_a_01.occupancy", "semantic_type": "percentage", "unit": "%"},
        ],
        "capabilities": ["capability.parking.read_occupancy"],
        "template_ref": "template.parking.zone",
        "bindings": [{"source": "gis", "source_id": "geojson-parking-zone-a-001", "lod": 100}],
        "relationships": [{"type": "depends_on", "target": "GA-11", "direction": "directed"}],
    },
    "GA-19": {
        "id": "GA-19",
        "code": "asset.park.waste.compactor_01",
        "name": "Waste Compactor-01",
        "category": "waste",
        "domain": "waste",
        "points": [
            {"id": "point-19-01", "code": "point.park.waste.compactor_01.fill_level", "semantic_type": "percentage", "unit": "%"},
        ],
        "capabilities": ["capability.waste.read_level"],
        "template_ref": "template.waste.compactor",
        "bindings": [],
        "relationships": [],
    },
    "GA-20": {
        "id": "GA-20",
        "code": "asset.park.it.server_rack_01",
        "name": "Server Rack-01",
        "category": "it",
        "domain": "it",
        "points": [
            {"id": "point-20-01", "code": "point.park.it.server_rack_01.cpu_temp", "semantic_type": "temperature", "unit": "degC"},
            {"id": "point-20-02", "code": "point.park.it.server_rack_01.uptime_hours", "semantic_type": "duration", "unit": "h"},
        ],
        "capabilities": ["capability.it.reboot_server"],
        "template_ref": "template.it.server",
        "bindings": [{"source": "bim", "source_id": "ifc-it-rack-001", "lod": 200}],
        "relationships": [{"type": "supplies", "target": "GA-01", "direction": "directed"}],
    },
}

# Validation rules
VALIDATION_RULES = {
    "VAL-01": {"check": "asset_code_pattern", "severity": "ERROR"},
    "VAL-02": {"check": "category_classification", "severity": "ERROR"},
    "VAL-03": {"check": "point_no_protocol_fields", "severity": "ERROR"},
    "VAL-04": {"check": "capability_safety_level", "severity": "ERROR"},
    "VAL-05": {"check": "template_instantiation", "severity": "ERROR"},
    "VAL-06": {"check": "binding_source_valid", "severity": "ERROR"},
    "VAL-07": {"check": "relationship_acyclic", "severity": "ERROR"},
    "VAL-08": {"check": "scene_binding_possible", "severity": "WARN"},
    "VAL-09": {"check": "kpi_formula_valid", "severity": "WARN"},
    "VAL-10": {"check": "alarm_escalation_complete", "severity": "WARN"},
}

ASSET_CODE_PATTERN = r"^asset\.(park|factory)\.(spatial|hvac|energy|water|security|transport|environment|production|fire|elevator|access|parking|waste|green|it|facility)\.[a-z_][a-z0-9_]*$"
