apiVersion: v1
kind: ResourceQuota
metadata:
  name: dt-lite-prod-quota
  namespace: dt-lite-prod
spec:
  hard:
    requests.cpu: "32"
    requests.memory: 64Gi
    limits.cpu: "64"
    limits.memory: 128Gi
    pods: "200"
