apiVersion: v1
kind: Service
metadata:
  name: ai
  namespace: dtlite
  labels:
    app: ai
spec:
  type: ClusterIP
  selector:
    app: ai
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
