apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ai
  namespace: dtlite
  labels:
    app: ai
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ai
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - dtlite
