apiVersion: dt-lite.io/v1
kind: MappingProfile
metadata:
  name: mapping-park-2
  namespace: smart-park
  labels:
    app: dt-lite-smart-park
spec:
  code: mapping.park.temp.2
  displayName: "Temp 映射 2"
  source:
    system: bms
    point: "temp_2"
    protocol: modbus
    address: "192.168.1.2"
    register: 40002
  target:
    asset: asset.park.building.01
    property: "temp_value"
  transform:
    type: raw_to_physical
    scale: 0.1
    offset: 0
  metadata:
    version: v1.0.0
    created: 2026-09-22
